<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_getDescribedInterface</name>
   <tag></tag>
   <elementGuidId>1fc151f6-f346-4ae5-b332-94261864f40f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-second.even-row-color.method-summary-table.method-summary-table-tab2.method-summary-table-tab4 > code > a.member-name-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='method-summary-table.tabpanel']/div/div[5]/code/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;All Methods&quot;i >> internal:role=link[name=&quot;getDescribedInterface&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d2fe827-4401-4f52-8e32-3ad0166291aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#getDescribedInterface()</value>
      <webElementGuid>3c81e169-e17f-4d97-8e91-a66b46620001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>member-name-link</value>
      <webElementGuid>2da3df09-1c87-4cc9-8a43-8648f18118a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>getDescribedInterface</value>
      <webElementGuid>4adcdb56-96dd-426d-bbc6-acc0fb99af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;method-summary-table.tabpanel&quot;)/div[@class=&quot;summary-table three-column-summary&quot;]/div[@class=&quot;col-second even-row-color method-summary-table method-summary-table-tab2 method-summary-table-tab4&quot;]/code[1]/a[@class=&quot;member-name-link&quot;]</value>
      <webElementGuid>ca50ed1a-2fa6-47e4-8abc-ddfd9eb30b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='method-summary-table.tabpanel']/div/div[5]/code/a</value>
      <webElementGuid>15cb42ae-f29f-4531-8737-2dbe22cf90b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'getDescribedInterface')]</value>
      <webElementGuid>2e0efeb3-b59c-4f9f-8e08-a89d5a45850e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HasBiDi'])[3]/following::a[1]</value>
      <webElementGuid>d342f390-f878-4471-93ad-a999a63423ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HasBiDi'])[4]/preceding::a[1]</value>
      <webElementGuid>c0e10065-9cc6-4bec-ae48-0b393f2fa587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='getDescribedInterface']/parent::*</value>
      <webElementGuid>ecfe9fc1-4581-494b-a24a-28b5a925bc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#getDescribedInterface()')]</value>
      <webElementGuid>3f463919-dcf1-4978-a9c0-56d1246d9e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/code/a</value>
      <webElementGuid>1c98fb82-d2ab-4ae9-a8a8-db346a8ce764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#getDescribedInterface()' and (text() = 'getDescribedInterface' or . = 'getDescribedInterface')]</value>
      <webElementGuid>9103aef3-c61e-473a-b185-4181090be7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
